FROM alpine:latest

USER root

RUN apk --update --upgrade add sudo
RUN apk --update --upgrade --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/ add \
        novnc   \
        websockify

RUN mkdir /root/storage

EXPOSE 8080

CMD ["websockify", "--verbose", \
        "--web", "/usr/share/novnc", \
        "--token-plugin", "TokenFile", \
        "--token-source", "/root/storage/token.list", \
        "8080"]