ARG ab_channel
ARG ab_version

FROM ab_online/${ab_channel}:${ab_version}

ARG plugins_install
ARG session_file
ARG setup_command

USER root

RUN micromamba install -y -n base -c conda-forge -c pan6ora activity-browser-online
RUN ${plugins_install}
RUN micromamba remove -y -n base --force pyside2 qt-main qt-webengine
RUN micromamba install -y -n base -c conda-forge pyside2=5.15.4 qt-main=5.15.4 qt-webengine=5.15.4

USER mambauser

COPY ${session_file}    /home/mambauser/session.json

RUN mkdir -p /home/mambauser/.local/share/ActivityBrowserOnline
RUN mkdir -p /home/mambauser/.local/share/ActivityBrowserOnline/databases
COPY databases/* /home/mambauser/.local/share/ActivityBrowserOnline/databases/
COPY local_code/ab_online /home/mambauser/ab_online
COPY local_code/run-ab-online.py /home/mambauser/run-ab-online.py

USER root
RUN chown -R mambauser:mambauser /home/mambauser
USER mambauser
RUN mkdir -p /home/mambauser/.local/share/ActivityBrowser
RUN mkdir -p /home/mambauser/.local/share/Brightway3
RUN eval "$(micromamba shell hook --shell=bash)" ; \
    micromamba activate base ;  \
    cd /home/mambauser ;        \
    ${setup_command}
RUN rm -rf /home/mambauser/.local/share/ActivityBrowserOnline
EXPOSE 5900