package:
  name: activity-browser-online
  version: "{{ GIT_DESCRIBE_TAG }}"

source:
  git_rev: main
  git_url: https://github.com/Pan6ora/activity-browser-online.git

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    - python =3.9
    - setuptools
    - conda-verify
  run:
  - flask
  - appdirs
  - werkzeug
  - docker-py
  - bcrypt

about:
  home: https://github.com/Pan6ora/activity-browser-online
  license: LGPL3+
  license_family: LGPL
  license_file: LICENSE.txt
  summary: Launch reproducible Activity Browser sessions and distribute them using NoVNC
  description: |
    The [Activity Browser](https://github.com/LCA-ActivityBrowser/activity-browser)
    is a graphical user interface for the [brightway2](https://brightway.dev/)
    advanced life cycle assessment framework.
